# Generated by Django 2.1.15 on 2020-01-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0007_auto_20190529_1419'),
        ('users', '0017_auto_20191020_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(verbose_name='klucz prywatny')),
                ('public_key', models.TextField(verbose_name='klucz publiczny')),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta')),
            ],
            options={
                'verbose_name': 'klucze RSA',
                'verbose_name_plural': 'klucze RSA',
            },
        ),
        migrations.CreateModel(
            name='UsedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.RSAKeys', verbose_name='ankieta')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'wykorzystany bilet',
                'verbose_name_plural': 'wykorzystane bilety',
            },
        ),
    ]
