# Generated by Django 2.1.15 on 2020-01-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_auto_20191020_1023'),
        ('poll', '0007_auto_20190529_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'wygenerowany bilet',
                'verbose_name_plural': 'wygenerowane bilety',
            },
        ),
        migrations.CreateModel(
            name='RSAKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(verbose_name='klucz prywatny')),
                ('public_key', models.TextField(verbose_name='klucz publiczny')),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta')),
            ],
            options={
                'verbose_name': 'klucze RSA',
                'verbose_name_plural': 'klucze RSA',
            },
        ),
        migrations.CreateModel(
            name='UsedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(verbose_name='bilet')),
                ('signed_ticket', models.TextField(verbose_name='podpisany bilet')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta')),
            ],
            options={
                'verbose_name': 'wykorzystany bilet',
                'verbose_name_plural': 'wykorzystane bilety',
            },
        ),
        migrations.AddField(
            model_name='generatedticket',
            name='keys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.RSAKeys', verbose_name='ankieta'),
        ),
        migrations.AddField(
            model_name='generatedticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='student'),
        ),
    ]
