# Generated by Django 2.1.8 on 2019-05-18 22:00

import apps.enrollment.courses.models.group
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_courseinformation_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[(apps.enrollment.courses.models.group.GroupType('1'), 'wykład'), (apps.enrollment.courses.models.group.GroupType('2'), 'ćwiczenia'), (apps.enrollment.courses.models.group.GroupType('3'), 'pracownia'), (apps.enrollment.courses.models.group.GroupType('5'), 'ćwiczenio-pracownia'), (apps.enrollment.courses.models.group.GroupType('6'), 'seminarium'), (apps.enrollment.courses.models.group.GroupType('7'), 'lektorat'), (apps.enrollment.courses.models.group.GroupType('8'), 'WF'), (apps.enrollment.courses.models.group.GroupType('9'), 'repetytorium'), (apps.enrollment.courses.models.group.GroupType('10'), 'projektu')], max_length=2, verbose_name='typ zajęć'),
        ),
    ]
