# Generated by Django 3.0.5 on 2020-04-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_term_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 'Parter'), (1, 'I piętro'), (2, 'II piętro'), (3, 'III piętro')], null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.IntegerField(choices=[(0, 'Sala wykładowa'), (1, 'Sala ćwiczeniowa'), (2, 'Pracownia komputerowa - Windows'), (3, 'Pracownia komputerowa - Linux'), (4, 'Pracownia dwusystemowa (Winodws+Linux)'), (5, 'Poligon (109)')], default=1, verbose_name='typ'),
        ),
        migrations.AlterField(
            model_name='group',
            name='extra',
            field=models.CharField(blank=True, choices=[('', ''), ('pierwsez 7 tygodni', 'pierwsze 7 tygodni'), ('drugie 7 tygodni', 'drugie 7 tygodni'), ('grupa rezerwowa', 'grupa rezerwowa'), ('grupa licencjacka', 'grupa licencjacka'), ('grupa magisterska', 'grupa magisterska'), ('grupa zaawansowana', 'grupa zaawansowana'), ('zajęcia na mat.', 'zajęcia na matematyce'), ('wykład okrojony', 'wykład okrojony'), ('grupa 1', 'grupa 1'), ('grupa 2', 'grupa 2'), ('grupa 3', 'grupa 3'), ('grupa 4', 'grupa 4'), ('grupa 5', 'grupa 5'), ('pracownia linuksowa', 'pracownia linuksowa'), ('grupa anglojęzyczna', 'grupa anglojęzyczna'), ('I rok', 'I rok'), ('II rok', 'II rok'), ('ISIM', 'ISIM'), ('hidden', 'grupa ukryta')], default='', max_length=20, verbose_name='dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('1', 'wykład'), ('2', 'ćwiczenia'), ('3', 'pracownia'), ('5', 'ćwiczenio-pracownia'), ('6', 'seminarium'), ('7', 'lektor'), ('8', 'WF'), ('9', 'repetytorium'), ('10', 'projekt'), ('11', 'tutoring'), ('12', 'proseminarium')], max_length=2, verbose_name='typ zajęć'),
        ),
        migrations.DeleteModel(
            name='StudentPointsView',
        ),
    ]
