# Generated by Django 3.0.4 on 2020-03-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_term_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('1', 'wykład'), ('2', 'ćwiczenia'), ('3', 'pracownia'), ('5', 'ćwiczenio-pracownia'), ('6', 'seminarium'), ('7', 'lektor'), ('8', 'WF'), ('9', 'repetytorium'), ('10', 'projekt'), ('11', 'tutoring'), ('12', 'proseminarium')], max_length=2, verbose_name='typ zajęć'),
        ),
        migrations.DeleteModel(
            name='StudentPointsView',
        ),
    ]
