# Generated by Django 3.0.4 on 2020-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20200403_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.IntegerField(blank=True, choices=[('0', 'Parter'), ('1', 'I piętro'), ('2', 'II piętro'), ('3', 'III piętro')], null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.IntegerField(choices=[('0', 'Sala wykładowa'), ('1', 'Sala ćwiczeniowa'), ('2', 'Pracownia komputerowa - Windows'), ('3', 'Pracownia komputerowa - Linux'), ('4', 'Pracownia dwusystemowa (Winodws+Linux)'), ('5', 'Poligon (109)')], default=1, verbose_name='typ'),
        ),
    ]
