SCHEDULER_BASE = 'http://scheduler.gtch.eu'

URL_LOGIN = SCHEDULER_BASE + '/admin/login/'
URL_CONFIG = SCHEDULER_BASE + '/scheduler/api/config/{id}/'

# The mapping between group types in scheduler and enrollment system
# w (wykład), p (pracownia), c (ćwiczenia), s (seminarium), r (ćwiczenio-pracownia),
# e (repetytorium), o (projekt), t (tutoring), m (proseminarium)
GROUP_TYPES = {'w': '1', 'e': '9', 'c': '2', 'p': '3',
               'r': '5', 's': '6', 'o': '10', 't': '11', 'm': '12'}

# The default limits for group types
LIMITS = {'1': 300, '9': 300, '2': 20, '3': 15, '5': 18, '6': 15, '10': 15}

COURSES_MAP = {
    'MATEMATYKA DYSKRETNA L': 'MATEMATYKA DYSKRETNA (L)',
    'MATEMATYKA DYSKRETNA M': 'MATEMATYKA DYSKRETNA (M)',
    'OCHRONA WŁASNOŚCI INTELEKTUALNEJ (ZIMA)': 'OCHRONA WŁASNOŚCI INTELEKTUALNEJ',
    'PROJEKT DYPLOMOWY (ZIMA)': 'PROJEKT DYPLOMOWY',
    'PROJEKT: BUDOWA I ROZWÓJ ANALOGU ŁAZIKA MARSJAŃSKIEGO (ZIMA)': 'PROJEKT: BUDOWA I ROZWÓJ ANALOGU ŁAZIKA MARSJAŃSKIEGO',
    'PROJEKT: ROZWÓJ SCHEDULERA (ZIMA)': 'PROJEKT: ROZWÓJ SCHEDULERA',
    'PROJEKT: ROZWÓJ SYSTEMU ZAPISÓW (ZIMA)': 'PROJEKT: ROZWÓJ SYSTEMU ZAPISÓW',
    'TUTORING DATA SCIENCE (ZIMA)': 'MENTORING FOR DATA SCIENCE',
    'TUTORING INFORMATYKA (ZIMA)': 'TUTORING',
    'TUTORING ISIM (ZIMA)': 'TUTORING ISIM',
    'ANALIZA NUMERYCZNA L': 'ANALIZA NUMERYCZNA (L)',
    'ANALIZA NUMERYCZNA M': 'ANALIZA NUMERYCZNA (M)',
    'INNOVATIVE PROJECTS BY NOKIA (ZIMA)': 'INNOVATIVE PROJECTS BY NOKIA',
    'PRAKTYKA ZAWODOWA 3 TYGODNIE': 'PRAKTYKA ZAWODOWA - TRZY TYGODNIE',
    'PRAKTYKA ZAWODOWA 4 TYGODNIE': 'PRAKTYKA ZAWODOWA - CZTERY TYGODNIE',
    'PRAKTYKA ZAWODOWA 5 TYGODNI': 'PRAKTYKA ZAWODOWA - PIĘĆ TYGODNI',
    'PRAKTYKA ZAWODOWA 6 TYGODNI': 'PRAKTYKA ZAWODOWA - SZEŚĆ TYGODNI',
    'KURS 1/2: ODZYSKIWANIE DANYCH': 'KURS-½: ODZYSKIWANIE DANYCH',
    'SEMINARIUM: BEZPIECZEŃSTWO I OCHRONA INFORMACJI': 'PROSEMINARIUM: BEZPIECZEŃSTWO I OCHRONA INFORMACJI',
}

COURSES_DONT_IMPORT = [
    'ANALIZA MATEMATYCZNA I',
    'ANALIZA MATEMATYCZNA II',
    'ANALIZA MATEMATYCZNA III',
    'ALGEBRA 1',
    'ALGEBRA I',
    'ALGEBRA II',
    'ALGEBRA LINIOWA 1R',
    'ALGEBRA LINIOWA 2',
    'ALGEBRA LINIOWA 2R',
    'MIARA I CAŁKA',
    'FUNKCJE ANALITYCZNE 1',
    'RÓWNANIA RÓŻNICZKOWE 1',
    'RÓWNANIA RÓŻNICZKOWE 1R',
    'TEORIA PRAWDOPODOBIEŃSTWA 1',
    'TOPOLOGIA']
