# Generated by Django 2.1.15 on 2020-01-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20190510_2314'),
        ('poll', '0007_auto_20190529_1419'),
    ]

    operations = [
    ]
