# Generated by Django 2.1.13 on 2019-12-16 22:35
"""
This migration creates a single instance of models.ThesesSystemSettings;
this is to allow to edit the configuration via the admin interface,
without changing settings.py and restarting the app
"""

import apps.theses.enums
import apps.theses.validators
from apps.theses.users import THESIS_BOARD_GROUP_NAME
from django.db import migrations, models
import django.db.models.deletion


def create_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).create(name=THESIS_BOARD_GROUP_NAME)


def remove_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).filter(name=THESIS_BOARD_GROUP_NAME).delete()


DEFAULT_REQUIRED_THESIS_VOTES = 3


def create_thesis_settings(apps, schema_editor):
    ThesesSystemSettings = apps.get_model("theses", "ThesesSystemSettings")
    db_alias = schema_editor.connection.alias
    ThesesSystemSettings.objects.using(db_alias).create(
        num_required_votes=DEFAULT_REQUIRED_THESIS_VOTES
    )


def remove_system_settings(apps, schema_editor):
    ThesesSystemSettings = apps.get_model("theses", "ThesesSystemSettings")
    db_alias = schema_editor.connection.alias
    ThesesSystemSettings.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_remove_program_type_of_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesesSystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('num_required_votes', models.SmallIntegerField(validators=[
                 apps.theses.validators.validate_num_required_votes], verbose_name='Liczba głosów wymaganych do zaakceptowania')),
                ('master_rejecter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Employee', validators=[
                 apps.theses.validators.validate_master_rejecter], verbose_name='Członek komisji odpowiedzialny za zwracanie prac do poprawek')),
            ],
            options={
                'verbose_name': 'ustawienia systemu prac dyplomowych',
                'verbose_name_plural': 'ustawienia systemu prac dyplomowych',
            },
        ),
        migrations.RunPython(create_group, remove_group),
        migrations.RunPython(create_thesis_settings, remove_system_settings)
    ]
