# Generated by Django 2.1.13 on 2019-12-17 00:30

import apps.theses.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_program_type_of_points'),
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(apps.theses.enums.ThesisVote(1), 'brak głosu'), (apps.theses.enums.ThesisVote(2), 'odrzucona'), (apps.theses.enums.ThesisVote(3), 'zaakceptowana')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_owner', to='users.Employee')),
            ],
            options={
                'verbose_name': 'głos',
                'verbose_name_plural': 'głosy',
            },
        ),
        migrations.AddField(
            model_name='thesis',
            name='votes',
            field=models.ManyToManyField(blank=True, to='theses.Vote'),
        ),
    ]
