# Generated by Django 2.1.13 on 2019-10-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_program_type_of_points'),
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_author', to='users.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='thesis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='thesis',
            name='rejection_reasons',
            field=models.ManyToManyField(to='theses.Remark', verbose_name='rejection_reasons'),
        ),
    ]
