# Generated by Django 2.1.13 on 2020-01-07 01:07

import apps.theses.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_program_type_of_points'),
        ('theses', '0002_auto_20191217_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesesSystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_required_votes', models.SmallIntegerField(validators=[apps.theses.validators.validate_num_required_votes], verbose_name='Liczba głosów wymaganych do zaakceptowania')),
                ('master_rejecter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Employee', validators=[apps.theses.validators.validate_master_rejecter], verbose_name='Członek komisji odpowiedzialny za zwracanie prac do poprawek')),
            ],
            options={
                'verbose_name': 'ustawienia systemu prac dyplomowych',
                'verbose_name_plural': 'ustawienia systemu prac dyplomowych',
            },
        ),
    ]
