# Generated by Django 2.1.13 on 2019-11-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_auto_20191030_0005'),
        ('theses', '0003_add_thesis_board_member_group'),
    ]

    operations = [
    ]
