# Generated by Django 2.1.13 on 2019-11-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_merge_20191105_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name': 'praca dyplomowa', 'verbose_name_plural': 'prace dyplomowe'},
        ),
        migrations.AddField(
            model_name='remark',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='rejection_reasons',
            field=models.ManyToManyField(blank=True, to='theses.Remark'),
        ),
    ]
