# Generated by Django 2.1.13 on 2019-12-15 19:03

import apps.theses.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_auto_20191118_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(apps.theses.enums.ThesisStatus(1), 'weryfikowana przez komisję'), (apps.theses.enums.ThesisStatus(2), 'zwrócona do poprawek'), (apps.theses.enums.ThesisStatus(3), 'zaakceptowana'), (apps.theses.enums.ThesisStatus(4), 'w realizacji'), (apps.theses.enums.ThesisStatus(5), 'obroniona')], null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
