# Generated by Django 2.1.15 on 2019-12-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_auto_20191118_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'verbose_name': 'uwaga', 'verbose_name_plural': 'uwagi'},
        ),
    ]
