---
- hosts: all

  become: yes
  
  vars:
    NODEJS_VERSION: "6"
    ansible_distribution_release: "xenial"
  
  tasks:
    
    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
    
    - name: Instal yarn
      package:
        name: yarn
        state: present
    
    - debug:
        msg: Install Python 3.6...
    - name: Install python3
      apt:
        name: python3
    - name: Install python3-venv
      apt:
        name: python3-venv
    
    - debug:
        msg: Install Redis...
    - name: Install redis
      apt:
        name: redis-server
    
    - name: Install tools
      apt:
        name:
        - git
        - libpq-dev
        - unzip
        - libc6-dev
        - libjpeg62-dev
        - libfreetype6-dev
        - xvfb
        - firefox
        - memcached